In [1]:
import numpy as np

In [17]:
a = np.array([1,2,3], dtype="int16")

In [3]:
print(a)

[1 2 3]


In [7]:
b = np.array([[1.2,3.2,2.3333],[1,2,3]])

In [8]:
print(b)

[[1.2    3.2    2.3333]
 [1.     2.     3.    ]]


# nothing to do
hello i am pekka

In [ ]:
b.ndim 

: 

In [10]:
b.ndim
a.ndim

1

In [11]:
b.ndim

2

In [12]:
a.shape

(3,)

In [13]:
b.shape

(2, 3)

In [14]:
b.dtype

dtype('float64')

In [18]:
a.dtype

dtype('int16')

In [19]:
b.itemsize

8

In [20]:
b.size

6

In [21]:
a.size

3

In [22]:
b.size*b.itemsize

48

In [24]:
b.nbytes

48

# accessing or changing specific rows and columns

In [25]:
print(b[0, :])

[1.2    3.2    2.3333]


In [26]:
print(b[:,1])

[3.2 2. ]


In [27]:
print(b
     )

[[1.2    3.2    2.3333]
 [1.     2.     3.    ]]


In [31]:
c = np.zeros((2,3,4,3))

In [32]:
print(c)

[[[[0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]]

  [[0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]]

  [[0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]]]


 [[[0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]]

  [[0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]]

  [[0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]]]]


In [33]:
c = np.full((2,3), 99)
print(c)

[[99 99 99]
 [99 99 99]]


In [34]:
np.full(a.shape, 33)

array([33, 33, 33])

In [35]:
np.full_like(a, 33)

array([33, 33, 33], dtype=int16)

In [36]:
d = np.full((5,5),1)
print(d)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [40]:
d[1:4,1:4] = 0

In [41]:
print(d)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


In [42]:
d[2,2] = 9

In [43]:
d

array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 9, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]])

# hello
## hello2

In [44]:
np.cos(a)

array([ 0.5403023, -0.4161468, -0.9899925], dtype=float32)

### Linear Algebra

In [45]:
a = np.array([[1,2],[1,2],[1,2]])
b = np.array([[1,2,3],[1,2,3]])

a.ndim

2

In [46]:
b.ndim

2

In [47]:
a

array([[1, 2],
       [1, 2],
       [1, 2]])

In [48]:
b

array([[1, 2, 3],
       [1, 2, 3]])

In [49]:
np.matmul(a,b)

array([[3, 6, 9],
       [3, 6, 9],
       [3, 6, 9]])

In [51]:
c = np.identity(5)
np.linalg.det(c)

1.0

In [54]:
v1 = np.array([1,2,3,4])
v2 = np. array([5,6,7,8])
np.vstack([v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [58]:
np.hstack((v2,v1))

array([5, 6, 7, 8, 1, 2, 3, 4])